BankWebApp/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BankWebApp.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public class AccessDeniedModel : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

BankWebApp/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace BankWebApp.Areas.Identity.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;

        public ConfirmEmailModel(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string StatusMessage { get; set; }
        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
            var result = await _userManager.ConfirmEmailAsync(user, code);
            StatusMessage = result.Succeeded ? "Thank you for confirming your email." : "Error confirming your email.";
            return Page();
        }
    }
}

BankWebApp/Areas/Identity/Pages/Account/ConfirmEmailChange.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace BankWebApp.Areas.Identity.Pages.Account
{
    public class ConfirmEmailChangeModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public ConfirmEmailChangeModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string StatusMessage { get; set; }

        public async Task<IActionResult> OnGetAsync(string userId, string email, string code)
        {
            if (userId == null || email == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
            var result = await _userManager.ChangeEmailAsync(user, email, code);
            if (!result.Succeeded)
            {
                StatusMessage = "Error changing email.";
                return Page();
            }

            // In our UI email and user name are one and the same, so when we update the email
            // we need to update the user name.
            var setUserNameResult = await _userManager.SetUserNameAsync(user, email);
            if (!setUserNameResult.Succeeded)
            {
                StatusMessage = "Error changing user name.";
                return Page();
            }

            await _signInManager.RefreshSignInAsync(user);
            StatusMessage = "Thank you for confirming your email change.";
            return Page();
        }
    }
}

BankWebApp/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace BankWebApp.Areas.Identity.Pages.Account
{
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _emailSender;

        public ForgotPasswordModel(UserManager<IdentityUser> userManager, IEmailSender emailSender)
        {
            _userManager = userManager;
            _emailSender = emailSender;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return RedirectToPage("./ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please
                // visit https://go.microsoft.com/fwlink/?LinkID=532713
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                var callbackUrl = Url.Page(
                    "/Account/ResetPassword",
                    pageHandler: null,
                    values: new { area = "Identity", code },
                    protocol: Request.Scheme);

                await _emailSender.SendEmailAsync(
                    Input.Email,
                    "Reset Password",
                    $"Please reset your password by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            return Page();
        }
    }
}

BankWebApp/Areas/Identity/Pages/Account/ForgotPasswordConfirmation.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BankWebApp.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    [AllowAnonymous]
    public class ForgotPasswordConfirmation : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

BankWebApp/Areas/Identity/Pages/Account/Lockout.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BankWebApp.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    [AllowAnonymous]
    public class LockoutModel : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

BankWebApp/Areas/Identity/Pages/Account/Logout.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace BankWebApp.Areas.Identity.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LogoutModel> _logger;

        public LogoutModel(SignInManager<IdentityUser> signInManager, ILogger<LogoutModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        public async Task<IActionResult> OnPost(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                // This needs to be a redirect so that the browser performs a new
                // request and the identity for the user gets updated.
                return RedirectToPage();
            }
        }
    }
}

BankWebApp/Areas/Identity/Pages/Account/ResetPasswordConfirmation.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BankWebApp.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    [AllowAnonymous]
    public class ResetPasswordConfirmationModel : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

BankWebApp/Pages/Accounts/AccountCreate.cshtml.cs
using AutoMapper;
using DataAccessLibrary.Models;
using DataAccessLibrary.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ServicesLibrary;
using UtilityLibrary;


namespace BankWebApp.Pages.Accounts
{
    [Authorize(Roles = "Cashier,Admin")]
    public class AccountCreateModel : PageModel
    {
        private readonly ICustomerService _customerService;
        private readonly IAccountService _accountService;
        private readonly IMapper _mapper;

        public AccountCreateModel(ICustomerService customerService, IAccountService accountService, IMapper mapper)
        {
            _customerService = customerService;
            _accountService = accountService;
            _mapper = mapper;
        }

        public CustomerViewModel Customer { get; set; }
        public List<SelectListItem> DisponentOptions { get; set; }

        public List<SelectListItem> Frequencies { get; set; }

        public string Q { get; set; }

        [BindProperty]
        public CustomerViewModel Disponent { get; set; }

        [BindProperty]
        public string Frequency { get; set; }

        [BindProperty] 
        public int DisponentId { get; set; }

        public void OnGet(int customerId)
        {
            Frequencies = GetListItems.GetFrequency();
            var customer = _customerService.GetCustomer(customerId);
            Customer = _mapper.Map<CustomerViewModel>(customer);
        }

        public IActionResult OnPostCreate(int customerId)
        {
            Frequencies = GetListItems.GetFrequency();
            Customer disponent = new();
            var customer = _customerService.GetCustomer(customerId);
            Customer = _mapper.Map<CustomerViewModel>(customer);
            if (DisponentId != 0)
            {
                disponent = _customerService.GetCustomer(DisponentId);
                Disponent = _mapper.Map<CustomerViewModel>(disponent);
            }
            var status = _accountService.CreateAccount(customerId, DisponentId, Frequency);
            if (status == ErrorCode.Success)
            {
                if (DisponentId != 0)
                {
                    TempData["successMessage"] = $"Client Account for ' {customer.Givenname} {customer.Surname} ' was created successfully!" +
                                          $" and a management account has been created for ' {disponent.Givenname} {disponent.Surname} '";
                }
                else
                {
                    TempData["successMessage"] = $"Client Account for ' {customer.Givenname} {customer.Surname} ' was created successfully!";
                }
                return RedirectToPage("/Accounts/Accounts", new { customerId });
            }

            if (status == ErrorCode.Error)
            {
                ViewData["Message"] = $"There was an error when trying to create the account please try again later.";
                ModelState.AddModelError("Account", "Something went wrong.");
            }
            return Page();
        }

        public IActionResult OnGetFetchInfo(string q)
        {
            var disponents = _customerService.GetCustomerForDisposition(q);

            var disponentOptions = disponents.Select(x => new SelectListItem
            {
                Value = x.CustomerId.ToString(),
                Text = $"{x.Givenname} {x.Surname} - Id {x.CustomerId}"
            }).ToList();

            return new JsonResult(disponentOptions);
        }
    }
}

BankWebApp/Pages/Accounts/AccountCreate.cshtml
@page
@model BankWebApp.Pages.Accounts.AccountCreateModel
@{
    ViewData["Title"] = "- Create Account";
    var errorMsg = ViewData["Message"]?.ToString();
}

<section class="section-fixed">
    <div id="page-section-1" class="section-rel-fixed">

        <div class="customer-card">
            <div class="customer-card-meta-flex">
                <a class="page-navigator-back-btn"
                   asp-page="/Accounts/Accounts"
                   asp-route-customerId="@Model.Customer.CustomerId">
                    <i class="fa-solid fa-arrow-left"></i>
                </a>
                <div class="font-weight-4">
                    SETUP NEW ACCOUNT
                </div>
            </div>
            <div class="form-wrapper">
             
                <form method="post">
                    @if (!string.IsNullOrWhiteSpace(errorMsg))
                    {
                        <div class="error-msg font-weight-3">
                            @errorMsg
                        </div>
                    }
                    else
                    {
                        <div class="success-msg-placeholder">
                        </div>
                    }
                    <div class="form-box-inner">
                        <div class="form-box-inner-spacing">
                            <div>
                                <label asp-for="@Model.Frequency"></label>
                            </div>
                            <div>
                                <select asp-for="@Model.Frequency" asp-items="@Model.Frequencies">
                                    <option value="">-- select --</option>
                                </select>
                            </div>
                            <div class="form-box-span">
                                <span asp-validation-for="@Model.Frequency"></span>
                            </div>
                        </div>
                        <div class="form-box-inner-spacing">
                            <label class="" asp-for="Q">Optional - Add a disponent.</label>
                            <div class="form-box-search-select">
                                <div class="input-for-q">
                                    <input class="form-space-1" asp-for="Q" placeholder="Search"/>
                                </div>
                                <div class="select-for-q" id="select-for-q">
                                    <select class="form-space-2" asp-for="DisponentId" asp-items="@Model.DisponentOptions"></select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-btn">
                        <button class="font-weight-3" type="submit" asp-page-handler="Create" asp-route-customerId="@Model.Customer.CustomerId">
                            <div class="pulsate">
                                create
                            </div>
                        </button>
                    </div>
                    <img class="customer-img" src="/images/sky-scrapers.jpg" alt="sky scrapers"/>
                </form>
            </div>
        </div>
    </div>
</section>
@section Scripts
    {
    <script>
        $(document).ready(function () {
            $('#Q').on('keyup', function () {
                var q = $(this).val();
                $.ajax({
                    url: '/Accounts/AccountCreate?handler=FetchInfo',
                    data: { q: q },
                    success: function (result) {
                        var optionsHtml = '';
                        optionsHtml = '<option value=""></option>' + optionsHtml;
                        if (result.length === 0) {
                            $('#select-for-q').css('top', '0px');
                            $.each(result, function (index, option) {
                                optionsHtml += '<option value="' + option.value + '">' + option.text + '</option>';
                            });
                            $('#DisponentId').html(optionsHtml);
                            $('#DisponentId').prop('size', Math.min(result.length, 10));
                        } else {
                            $('#select-for-q').css('top', '28px');
                            $.each(result, function (index, option) {
                                optionsHtml += '<option value="' + option.value + '">' + option.text + '</option>';
                            });
                            $('#DisponentId').html(optionsHtml);
                            $('#DisponentId').prop('size', Math.min(result.length, 10));
                        }
                    }
                });
            });
            $('#DisponentId').on('change', function () {
                $(this).prop('size', 1);
                $('#select-for-q').css('top', '0px');
            });
            $('#Q').on('click', function () {
                $(this).val('');
            });
        });


    </script>

  
}